import { test, expect } from "@playwright/test";
import path from "path";
import fs from "fs";

// Fixture file paths
const VALID_IMAGE = path.join(__dirname, "fixtures", "test.png");
const LARGE_IMAGE = path.join(__dirname, "fixtures", "large.png");

test.beforeAll(() => {
    // Create fixtures folder if it doesn't exist
    const dir = path.join(__dirname, "fixtures");
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    // Create a valid 100×100 PNG using base64 generated by sharp.
    // This is a real PNG (not hand-crafted hex) so CRC checksums are correct
    // and sharp in the worker will process it without errors.
    if (!fs.existsSync(VALID_IMAGE)) {
        const PNG_VALID = Buffer.from(
            "iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAAAACXBIWXMAAAPoAAAD6AG1e1Jr" +
            "AAABFElEQVR4nO3WwQ1CAQzDUIb9KzGmd2AFLihFelInsJw0r+ede76D8ELq+VoXsAKrXySG" +
            "WYEVs9q+IzEMrJiVGPYvw1hnBVbMSgybl5HOCqyY1TxipkNgxazunwUfWDErMWxeRjorsGJW" +
            "84iZDoEVs7p/FnxgxazEsHkZ6azAilnNI2Y6BFbM6v5Z8IEVsxLD5mWkswIrZjWPmOkQWDGr" +
            "+2fBB1bMSgybl5HOCqyY1TxipkNgxazunwUfWDErMWxeRjorsGJW84iZDoEVs7p/FnxgxazE" +
            "sHkZ6azAilnNI2Y6BFbM6v5Z8IEVsxLD5mWkswIrZjWPmOkQWDGr+2fBB1bMSgybl5HOCqyY" +
            "1TxipkNgtTLrA6pwLLdpTh8fAAAAAElFTkSuQmCC",
            "base64"
        );
        fs.writeFileSync(VALID_IMAGE, PNG_VALID);
    }

    // Create a fake file > 20 MB to test size validation
    if (!fs.existsSync(LARGE_IMAGE)) {
        const buf = Buffer.alloc(21 * 1024 * 1024, 0); // 21 MB of zeros
        fs.writeFileSync(LARGE_IMAGE, buf);
    }
});

// ── Test 1: Happy path ──────────────────────────────────────────────────────
test("upload valid image → process → download button appears", async ({ page }) => {
    await page.goto("/");

    // Select file via the hidden input
    const input = page.locator('input[type="file"]');
    await input.setInputFiles(VALID_IMAGE);

    // Click upload — use { force: true } to bypass the floating-card CSS
    // animation that causes Playwright to report the button as "not stable"
    await page.getByRole("button", { name: /upload & proses/i }).click({ force: true });

    // Wait for either "Selesai" OR "Gagal" to appear first (up to 2 minutes),
    // then assert it is specifically "Selesai" — this avoids a 60s timeout if
    // the job finishes quickly with an error status.
    await expect(
        page.getByText(/selesai|gagal/i)
    ).toBeVisible({ timeout: 120_000 });

    await expect(
        page.getByText(/selesai/i)
    ).toBeVisible();

    // Download button must be visible
    await expect(
        page.getByRole("button", { name: /download hasil/i })
    ).toBeVisible();
});

// ── Test 2: Format validation ───────────────────────────────────────────────
test("upload non-image file → error message appears", async ({ page }) => {
    await page.goto("/");

    // Create a temporary .txt file
    const txtFile = path.join(__dirname, "fixtures", "test.txt");
    fs.writeFileSync(txtFile, "not an image");

    const input = page.locator('input[type="file"]');
    await input.setInputFiles(txtFile);

    // Validation error must appear
    await expect(
        page.getByText(/format tidak didukung/i)
    ).toBeVisible();

    // Upload button must be disabled
    await expect(
        page.getByRole("button", { name: /upload & proses/i })
    ).toBeDisabled();
});

// ── Test 3: Size validation ─────────────────────────────────────────────────
test("upload file > 20 MB → error message appears", async ({ page }) => {
    await page.goto("/");

    const input = page.locator('input[type="file"]');
    await input.setInputFiles(LARGE_IMAGE);

    // Size error must appear
    await expect(
        page.getByText(/ukuran file terlalu besar/i)
    ).toBeVisible();

    // Upload button must be disabled
    await expect(
        page.getByRole("button", { name: /upload & proses/i })
    ).toBeDisabled();
});